from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class StoryboardPanel(Base):
    """
    One storyboard panel per scene. This is a *text/diagram* storyboard
    (shot type, composition, key visual beat, framing notes) generated by
    app/ai/storyboard.py from the scene's parsed action lines, dominant
    emotion, and shot suggestion — not an AI-generated image. Image
    generation is a reasonable future extension but is out of scope here:
    it would need a separate image model, real storage/CDN for the
    generated frames, and meaningfully changes the cost/complexity of the
    pipeline, so panels are descriptive rather than pictorial for now.
    """

    __tablename__ = "storyboard_panels"

    id = Column(Integer, primary_key=True, index=True)
    scene_id = Column(Integer, ForeignKey("scenes.id"), nullable=False, unique=True)
    script_id = Column(Integer, ForeignKey("scripts.id"), nullable=False)

    panel_number = Column(Integer, nullable=False)
    shot_type = Column(String, nullable=False)
    camera_angle = Column(String, nullable=False)
    composition_notes = Column(Text, nullable=False)
    key_visual_elements = Column(Text, nullable=True)
    mood_lighting = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scene = relationship("Scene")
