/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldBuilderRouteImport } from './routes/world-builder'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as StoryGeneratorRouteImport } from './routes/story-generator'
import { Route as SoundLibraryRouteImport } from './routes/sound-library'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShotListRouteImport } from './routes/shot-list'
import { Route as ScriptUploadRouteImport } from './routes/script-upload'
import { Route as ScriptGeneratorRouteImport } from './routes/script-generator'
import { Route as ScriptCorrectionRouteImport } from './routes/script-correction'
import { Route as PropsRouteImport } from './routes/props'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationLibraryRouteImport } from './routes/location-library'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CharacterLibraryRouteImport } from './routes/character-library'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts.$scriptId'

const WorldBuilderRoute = WorldBuilderRouteImport.update({
  id: '/world-builder',
  path: '/world-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryGeneratorRoute = StoryGeneratorRouteImport.update({
  id: '/story-generator',
  path: '/story-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundLibraryRoute = SoundLibraryRouteImport.update({
  id: '/sound-library',
  path: '/sound-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotListRoute = ShotListRouteImport.update({
  id: '/shot-list',
  path: '/shot-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptUploadRoute = ScriptUploadRouteImport.update({
  id: '/script-upload',
  path: '/script-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptGeneratorRoute = ScriptGeneratorRouteImport.update({
  id: '/script-generator',
  path: '/script-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptCorrectionRoute = ScriptCorrectionRouteImport.update({
  id: '/script-correction',
  path: '/script-correction',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsRoute = PropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLibraryRoute = LocationLibraryRouteImport.update({
  id: '/location-library',
  path: '/location-library',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterLibraryRoute = CharacterLibraryRouteImport.update({
  id: '/character-library',
  path: '/character-library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/character-library': typeof CharacterLibraryRoute
  '/characters': typeof CharactersRoute
  '/credits': typeof CreditsRoute
  '/location-library': typeof LocationLibraryRoute
  '/login': typeof LoginRoute
  '/media-library': typeof MediaLibraryRoute
  '/props': typeof PropsRoute
  '/script-correction': typeof ScriptCorrectionRoute
  '/script-generator': typeof ScriptGeneratorRoute
  '/script-upload': typeof ScriptUploadRoute
  '/shot-list': typeof ShotListRoute
  '/signup': typeof SignupRoute
  '/sound-library': typeof SoundLibraryRoute
  '/story-generator': typeof StoryGeneratorRoute
  '/storyboard': typeof StoryboardRoute
  '/templates': typeof TemplatesRoute
  '/world-builder': typeof WorldBuilderRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/character-library': typeof CharacterLibraryRoute
  '/characters': typeof CharactersRoute
  '/credits': typeof CreditsRoute
  '/location-library': typeof LocationLibraryRoute
  '/login': typeof LoginRoute
  '/media-library': typeof MediaLibraryRoute
  '/props': typeof PropsRoute
  '/script-correction': typeof ScriptCorrectionRoute
  '/script-generator': typeof ScriptGeneratorRoute
  '/script-upload': typeof ScriptUploadRoute
  '/shot-list': typeof ShotListRoute
  '/signup': typeof SignupRoute
  '/sound-library': typeof SoundLibraryRoute
  '/story-generator': typeof StoryGeneratorRoute
  '/storyboard': typeof StoryboardRoute
  '/templates': typeof TemplatesRoute
  '/world-builder': typeof WorldBuilderRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/character-library': typeof CharacterLibraryRoute
  '/characters': typeof CharactersRoute
  '/credits': typeof CreditsRoute
  '/location-library': typeof LocationLibraryRoute
  '/login': typeof LoginRoute
  '/media-library': typeof MediaLibraryRoute
  '/props': typeof PropsRoute
  '/script-correction': typeof ScriptCorrectionRoute
  '/script-generator': typeof ScriptGeneratorRoute
  '/script-upload': typeof ScriptUploadRoute
  '/shot-list': typeof ShotListRoute
  '/signup': typeof SignupRoute
  '/sound-library': typeof SoundLibraryRoute
  '/story-generator': typeof StoryGeneratorRoute
  '/storyboard': typeof StoryboardRoute
  '/templates': typeof TemplatesRoute
  '/world-builder': typeof WorldBuilderRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/character-library'
    | '/characters'
    | '/credits'
    | '/location-library'
    | '/login'
    | '/media-library'
    | '/props'
    | '/script-correction'
    | '/script-generator'
    | '/script-upload'
    | '/shot-list'
    | '/signup'
    | '/sound-library'
    | '/story-generator'
    | '/storyboard'
    | '/templates'
    | '/world-builder'
    | '/scripts/$scriptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/character-library'
    | '/characters'
    | '/credits'
    | '/location-library'
    | '/login'
    | '/media-library'
    | '/props'
    | '/script-correction'
    | '/script-generator'
    | '/script-upload'
    | '/shot-list'
    | '/signup'
    | '/sound-library'
    | '/story-generator'
    | '/storyboard'
    | '/templates'
    | '/world-builder'
    | '/scripts/$scriptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/character-library'
    | '/characters'
    | '/credits'
    | '/location-library'
    | '/login'
    | '/media-library'
    | '/props'
    | '/script-correction'
    | '/script-generator'
    | '/script-upload'
    | '/shot-list'
    | '/signup'
    | '/sound-library'
    | '/story-generator'
    | '/storyboard'
    | '/templates'
    | '/world-builder'
    | '/scripts/$scriptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CharacterLibraryRoute: typeof CharacterLibraryRoute
  CharactersRoute: typeof CharactersRoute
  CreditsRoute: typeof CreditsRoute
  LocationLibraryRoute: typeof LocationLibraryRoute
  LoginRoute: typeof LoginRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  PropsRoute: typeof PropsRoute
  ScriptCorrectionRoute: typeof ScriptCorrectionRoute
  ScriptGeneratorRoute: typeof ScriptGeneratorRoute
  ScriptUploadRoute: typeof ScriptUploadRoute
  ShotListRoute: typeof ShotListRoute
  SignupRoute: typeof SignupRoute
  SoundLibraryRoute: typeof SoundLibraryRoute
  StoryGeneratorRoute: typeof StoryGeneratorRoute
  StoryboardRoute: typeof StoryboardRoute
  TemplatesRoute: typeof TemplatesRoute
  WorldBuilderRoute: typeof WorldBuilderRoute
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world-builder': {
      id: '/world-builder'
      path: '/world-builder'
      fullPath: '/world-builder'
      preLoaderRoute: typeof WorldBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-generator': {
      id: '/story-generator'
      path: '/story-generator'
      fullPath: '/story-generator'
      preLoaderRoute: typeof StoryGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-library': {
      id: '/sound-library'
      path: '/sound-library'
      fullPath: '/sound-library'
      preLoaderRoute: typeof SoundLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shot-list': {
      id: '/shot-list'
      path: '/shot-list'
      fullPath: '/shot-list'
      preLoaderRoute: typeof ShotListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script-upload': {
      id: '/script-upload'
      path: '/script-upload'
      fullPath: '/script-upload'
      preLoaderRoute: typeof ScriptUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script-generator': {
      id: '/script-generator'
      path: '/script-generator'
      fullPath: '/script-generator'
      preLoaderRoute: typeof ScriptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script-correction': {
      id: '/script-correction'
      path: '/script-correction'
      fullPath: '/script-correction'
      preLoaderRoute: typeof ScriptCorrectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props': {
      id: '/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof PropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-library': {
      id: '/location-library'
      path: '/location-library'
      fullPath: '/location-library'
      preLoaderRoute: typeof LocationLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-library': {
      id: '/character-library'
      path: '/character-library'
      fullPath: '/character-library'
      preLoaderRoute: typeof CharacterLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CharacterLibraryRoute: CharacterLibraryRoute,
  CharactersRoute: CharactersRoute,
  CreditsRoute: CreditsRoute,
  LocationLibraryRoute: LocationLibraryRoute,
  LoginRoute: LoginRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  PropsRoute: PropsRoute,
  ScriptCorrectionRoute: ScriptCorrectionRoute,
  ScriptGeneratorRoute: ScriptGeneratorRoute,
  ScriptUploadRoute: ScriptUploadRoute,
  ShotListRoute: ShotListRoute,
  SignupRoute: SignupRoute,
  SoundLibraryRoute: SoundLibraryRoute,
  StoryGeneratorRoute: StoryGeneratorRoute,
  StoryboardRoute: StoryboardRoute,
  TemplatesRoute: TemplatesRoute,
  WorldBuilderRoute: WorldBuilderRoute,
  ScriptsScriptIdRoute: ScriptsScriptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
